### PR TITLE
Windows compatibility

### PR DESCRIPTION
**Pull request by alxwrd**
hello @Antrikshy! happy hacktoberfest 🎃

This PR adds windows support by switching from `scripts` in the setup file, to `entry_point` and using `console_scripts`. https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point.

I've removed the `bin/ignr` script as these change seems to make it obsolete. If you'd prefer to keep it, let me know.

I've also tested all 4 examples in the README on my windows machine. Everything works ok 🎉

### CODE REVIEW

**Comment by Antrikshy** [comment]
Hey, thanks for the contribution! I may have broken some kind of GitHub PR-merge laziness record with this one.

If you still remember the details, could you walk me through testing this change locally? I have a Windows PC at hand, but it's not my primary development platform, especially with Python.

I tried cloning your branch, then running `pip install -e .` in it, which seems to link it up for testing. But just running `ignr` or `python -m ignr` doesn't work. The latter tells me

    `No module named ignr.__main__; 'ignr' is a package and cannot be directly executed`

To be fair, installing the currently published version using `pip install ignr` gives me the same thing.

I might be missing a step somewhere. Do Windows pip users manually add every new install to PATH?

**Comment by alxwrd** [comment]
Hey, I've just repulled this on my Windows machine too and it wasn't working for me either. I've got Python 3.8 installed, so I'm not sure if it's changes there or not?

I've just pushed a commit to address both issues. `console_scripts` uses python.dot.path with the colon `:` to denote a function call. `cli` isn't a function, so I'm not sure how I got this to work before?

I've also added a `__main__.py` file so you can do `python3 -m ignr`.

**Comment by Antrikshy** [comment]
This seems to work, with one small caveat. `argparse.ArgumentParser` shows an autogenerated help message if the user doesn't enter required arguments. With your changes, it looks like this:

    > python3 -m ignr
    usage: __main__.py [-h] (--list | --search TECH | --new TECH [TECH ...] | --preview TECH [TECH ...])
    __main__.py: error: one of the arguments --list/-l --search/-s --new/-n --preview/-p is required

Could you add [this little thing](https://stackoverflow.com/a/66611800/2005759) to make it say `python -m ignr`?

**Comment by alxwrd** [comment]
@Antrikshy, sure I've just pushed that. I've set it dependant on `sys.argv[0]`, as with `python -m ignr`, `sys.argv[0] == "ignr.py/ignr/__main__.py"`, and with `ignr`, `sys.argv[0] == "~/.local/bin/ignr"`.

```
$ python3 -m ignr
usage: python -m ignr [-h]
```

```
$ ignr
usage: ignr [-h]
```

**Comment by Antrikshy** [comment]
Looking good! Apologies for ~~git~~ignoring the PR for so long. Will release to PyPI shortly, when I get a chance.

**Comment by Antrikshy** [comment]
Update: [Done.](https://pypi.org/project/ignr/#history) Thanks for playing!

**Pull request merged**
